---
driver:
  name: vagrant

platforms:
  - name: ubuntu-14.04

suites:
  - name: zero_nine
    run_list:
      - recipe[apt::default]
      - recipe[influxdb::default]
    attributes:
      influxdb:
        version: "0.9.3"
