---
settings:
  parallel: true

driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[influxdb-test::default]
      - recipe[netstat]
    attributes:
