LineLength:
  Max: 200

SingleSpaceBeforeFirstArg:
  Enabled: false

HashSyntax:
  Enabled: false

NumericLiterals:
  Enabled: false

AbcSize:
  Enabled: false

MethodLength:
  Enabled: false

RescueModifier:
  Enabled: false
